export default interface ContentBlockProps {
  ariaDetails?: string
  children?: React.ReactNode
  backgroundColor?: string
  borderRadius?: string
  borderTop?: string
  borderBottom?: string
  fontColor?: string
  display?: string
  flexFlow?: string
  fontFamily?: string
  lineHeight?: string
  margin?: string
  maxWidth?: string
  outline?: string
  padding?: string
  width?: string
  textAlign?: string
  headerImgMaxWidth?: string
  headerImgPadding?: string
  footerImgMaxWidth?: string
  border?: string
  sectionWidth?: string
  sectionMargin?: string
  sectionPadding?: string
  h1Color?: string
  h1Display?: string
  h1FontFamily?: string
  h1FontSize?: string
  h1FontWeight?: string
  h1JustifyContent?: string
  h1LetterSpacing?: string
  h1LineHeight?: string
  h1Margin?: string
  h1MaxWidth?: string
  h1Padding?: string
  h1TextAlign?: string
  h1TextShadow?: string
  h1TextTransform?: string
  h2Color?: string
  h2Display?: string
  h2FontFamily?: string
  h2FontSize?: string
  h2FontWeight?: string
  h2JustifyContent?: string
  h2LetterSpacing?: string
  h2LineHeight?: string
  h2Margin?: string
  h2MaxWidth?: string
  h2Padding?: string
  h2TextAlign?: string
  h2TextShadow?: string
  h2TextTransform?: string
  h3Color?: string
  h3Display?: string
  h3FontFamily?: string
  h3FontSize?: string
  h3FontWeight?: string
  h3JustifyContent?: string
  h3LetterSpacing?: string
  h3LineHeight?: string
  h3Margin?: string
  h3MaxWidth?: string
  h3Padding?: string
  h3TextAlign?: string
  h3TextShadow?: string
  h3TextTransform?: string
  h4Color?: string
  h4Display?: string
  h4FontFamily?: string
  h4FontSize?: string
  h4FontWeight?: string
  h4JustifyContent?: string
  h4LetterSpacing?: string
  h4LineHeight?: string
  h4Margin?: string
  h4MaxWidth?: string
  h4Padding?: string
  h4TextAlign?: string
  h4TextShadow?: string
  h4TextTransform?: string
  h5Color?: string
  h5Display?: string
  h5FontFamily?: string
  h5FontSize?: string
  h5FontWeight?: string
  h5JustifyContent?: string
  h5LetterSpacing?: string
  h5LineHeight?: string
  h5Margin?: string
  h5MaxWidth?: string
  h5Padding?: string
  h5TextAlign?: string
  h5TextShadow?: string
  h5TextTransform?: string
  h6Color?: string
  h6Display?: string
  h6FontFamily?: string
  h6FontSize?: string
  h6FontWeight?: string
  h6JustifyContent?: string
  h6LetterSpacing?: string
  h6LineHeight?: string
  h6Margin?: string
  h6MaxWidth?: string
  h6Padding?: string
  h6TextAlign?: string
  h6TextShadow?: string
  h6TextTransform?: string
  aFontColor?: string
  aDisplay?: string
  aFontFamily?: string
  aFontSize?: string
  aFontWeight?: string
  aHoverColor?: string
  aJustifyContent?: string
  aLetterSpacing?: string
  aLineHeight?: string
  aMargin?: string
  aMaxWidth?: string
  aPadding?: string
  aTextAlign?: string
  aTextShadow?: string
  aTextTransform?: string
  articleColor?: string
  articleDisplay?: string
  articleFontFamily?: string
  articleFontSize?: string
  articleFontWeight?: string
  articleJustifyContent?: string
  articleLetterSpacing?: string
  articleLineHeight?: string
  articleMargin?: string
  articleMaxWidth?: string
  articlePadding?: string
  articleTextAlign?: string
  articleTextShadow?: string
  articleTextTransform?: string
  articleWidth?: string
  pColor?: string
  pDisplay?: string
  pFontFamily?: string
  pFontSize?: string
  pFontWeight?: string
  pJustifyContent?: string
  pLetterSpacing?: string
  pLineHeight?: string
  pMargin?: string
  pMaxWidth?: string
  pPadding?: string
  pTextAlign?: string
  pTextShadow?: string
  pTextTransform?: string
}
