export interface StyledButtonProps {
  $backgroundColor?: string
  $border?: string
  $borderRadius?: string
  $display?: string
  $fontFamily?: string
  $fontSize?: string
  $fontWeight?: string
  $hoverBackgroundColor?: string
  $hoverBorder?: string
  $hoverTextColor?: string
  $letterSpacing?: string
  $margin?: string
  $maxWidth?: string
  $outerMargin?: string
  $outerPadding?: string
  $padding?: string
  $position?: string
  $textAlign?: string
  $textColor?: string
  $textDecoration?: string
  $textTransform?: string
  $width?: string
}

export interface StyledContactFormProps {
  $buttonColor?: string
  $buttonFontColor?: string
  $buttonFontFamily?: string
  $buttonFontSize?: string
  $buttonFontWeight?: string
  $buttonLetterSpacing?: string
  $buttonMarginTop?: string
  $buttonPadding?: string
  $buttonTextTransform?: string
  $display?: string
  $errorFontColor?: string
  $errorFontFamily?: string
  $errorLetterSpacing?: string
  $errorTextTransform?: string
  $flexFlow?: string
  $fontFamily?: string
  $formMargin?: string
  $formWidth?: string
  $inputFontSize?: string
  $labelDisplay?: string
  $labelFontColor?: string
  $labelFontFamily?: string
  $labelFontSize?: string
  $labelFontWeight?: string
  $labelLetterSpacing?: string
  $labelLineHeight?: string
  $labelMargin?: string
  $labelTextAlign?: string
  $margin?: string
  $maxWidth?: string
  $padding?: string
  $textareaFontSize?: string
  $textTransform?: string
  $width?: string
}

export interface FormProps {
  buttonColor?: string
  buttonFontColor?: string
  buttonFontFamily?: string
  buttonFontSize?: string
  buttonFontWeight?: string
  buttonHoverColor?: string
  buttonLetterSpacing?: string
  buttonMarginTop?: string
  buttonPadding?: string
  buttonTextTransform?: string
  contactReply: string
  display?: string
  errorFontColor?: string
  errorFontFamily?: string
  errorLetterSpacing?: string
  errorTextTransform?: string
  flexFlow?: string
  fontFamily?: string
  formMargin?: string
  formWidth?: string
  inputFontSize?: string
  labelDisplay?: string
  labelFontColor?: string
  labelFontFamily?: string
  labelFontSize?: string
  labelFontWeight?: string
  labelLetterSpacing?: string
  labelLineHeight?: string
  labelMargin?: string
  labelTextAlign?: string
  margin?: string
  maxWidth?: string
  padding?: string
  submitButtonStyles?: any
  textareaColumns?: number
  textareaFontSize?: string
  textareaRows?: number
  textTransform?: string
  width?: string
}
