export interface StyledMenuCategoryProps {
  $backgroundColor?: string
  $h2Color?: string
  $h2Display?: string
  $h2FontFamily?: string
  $h2FontSize?: string
  $h2FontStyle?: string
  $h2FontWeight?: string
  $h2JustifyContent?: string
  $h2LetterSpacing?: string
  $h2LineHeight?: string
  $h2Margin?: string
  $h2MaxWidth?: string
  $h2Padding?: string
  $h2TextAlign?: string
  $h2TextShadow?: string
  $h2TextTransform?: string
  $h3Color?: string
  $h3Display?: string
  $h3FontFamily?: string
  $h3FontSize?: string
  $h3FontStyle?: string
  $h3FontWeight?: string
  $h3JustifyContent?: string
  $h3LetterSpacing?: string
  $h3LineHeight?: string
  $h3Margin?: string
  $h3MaxWidth?: string
  $h3Padding?: string
  $h3TextAlign?: string
  $h3TextShadow?: string
  $h3TextTransform?: string
  $h4Color?: string
  $h4Display?: string
  $h4FontFamily?: string
  $h4FontSize?: string
  $h4FontStyle?: string
  $h4FontWeight?: string
  $h4JustifyContent?: string
  $h4LetterSpacing?: string
  $h4LineHeight?: string
  $h4Margin?: string
  $h4MaxWidth?: string
  $h4Padding?: string
  $h4TextAlign?: string
  $h4TextShadow?: string
  $h4TextTransform?: string
  $h5Color?: string
  $h5Display?: string
  $h5FontFamily?: string
  $h5FontSize?: string
  $h5FontWeight?: string
  $h5JustifyContent?: string
  $h5LetterSpacing?: string
  $h5LineHeight?: string
  $h5Margin?: string
  $h5MaxWidth?: string
  $h5Padding?: string
  $h5TextAlign?: string
  $h5TextShadow?: string
  $h5TextTransform?: string
  $h6Color?: string
  $h6Display?: string
  $h6FontFamily?: string
  $h6FontSize?: string
  $h6FontWeight?: string
  $h6JustifyContent?: string
  $h6LetterSpacing?: string
  $h6LineHeight?: string
  $h6Margin?: string
  $h6MaxWidth?: string
  $h6Padding?: string
  $h6TextAlign?: string
  $h6TextShadow?: string
  $h6TextTransform?: string
  $orderNumber?: string
  $pFontFamily?: string
}

export interface StyledMenuItemProps {
  $border?: string
  $background?: string
  $borderRadius?: string
  $boxShadow?: string
  $display?: string
  $flexBasis?: string
  $flexFlow?: string
  $margin?: string
  $maxWidth?: string
  $padding?: string
  $width?: string
  $tableFontFamily?: string
  $tablePadding?: string
  $tableWidth?: string
  $tableDataLineHeight?: string
  $tableDataPadding?: string
  $menuItemBorderRadius?: string
  $menuItemBoxShadow?: string
  $pColor?: string
  $pDisplay?: string
  $pFontFamily?: string
  $pFontSize?: string
  $pFontWeight?: string
  $pJustifyContent?: string
  $pLetterSpacing?: string
  $pLineHeight?: string
  $pMargin?: string
  $pMaxWidth?: string
  $pPadding?: string
  $pTextAlign?: string
  $pTextShadow?: string
  $pTextTransform?: string
  $menuItemDisplay?: string
  $menuItemFlexBasis?: string
  $menuItemFlexFlow?: string
  $menuItemMargin?: string
  $menuItemMaxWidth?: string
  $menuItemName?: string
  $menuItemNameColor?: string
  $menuItemNameFontFamily?: string
  $menuItemNameFontSize?: string
  $menuItemNameFontWeight?: string
  $menuItemNameLetterSpacing?: string
  $menuItemNameLineHeight?: string
  $menuItemNameMaxWidth?: string
  $menuItemNamePadding?: string
  $menuItemNameTextAlign?: string
  $menuItemNameTextTransform?: string
  $menuItemPriceColor?: string
  $menuItemPriceFontFamily?: string
  $menuItemPriceFontSize?: string
  $menuItemPriceFontWeight?: string
  $menuItemPriceLetterSpacing?: string
  $menuItemPriceLineHeight?: string
  $menuItemPriceMaxWidth?: string
  $menuItemPricePadding?: string
  $menuItemPriceTextAlign?: string
  $menuItemPriceTextTransform?: string
}

export interface MenuItemProps {
  description?: string
  menuItemBackground?: string
  menuItemBorder?: string
  menuItemBorderRadius?: string
  menuItemBoxShadow?: string
  menuItemDescriptionColor?: string
  menuItemDescriptionFontFamily?: string
  menuItemDescriptionFontSize?: string
  menuItemDescriptionFontWeight?: string
  menuItemDescriptionLetterSpacing?: string
  menuItemDescriptionLineHeight?: string
  menuItemDescriptionMaxWidth?: string
  menuItemDescriptionPadding?: string
  menuItemDescriptionTextAlign?: string
  menuItemDescriptionTextTransform?: string
  menuItemDisplay?: string
  menuItemFlexBasis?: string
  menuItemFlexFlow?: string
  menuItemMargin?: string
  menuItemMaxWidth?: string
  menuItemNameColor?: string
  menuItemNameFontFamily?: string
  menuItemNameFontSize?: string
  menuItemNameFontWeight?: string
  menuItemNameLetterSpacing?: string
  menuItemNameLineHeight?: string
  menuItemNameMaxWidth?: string
  menuItemNamePadding?: string
  menuItemNameTextAlign?: string
  menuItemNameTextTransform?: string
  menuItemPadding?: string
  menuItemPriceColor?: string
  menuItemPriceFontFamily?: string
  menuItemPriceFontSize?: string
  menuItemPriceFontWeight?: string
  menuItemPriceLetterSpacing?: string
  menuItemPriceLineHeight?: string
  menuItemPriceMaxWidth?: string
  menuItemPricePadding?: string
  menuItemPriceTextAlign?: string
  menuItemPriceTextTransform?: string
  menuItemTableDataLineHeight?: string
  menuItemTableDataPadding?: string
  menuItemTableFontFamily?: string
  menuItemTablePadding?: string
  menuItemTableWidth?: string
  menuItemWidth?: string
  name?: string
  price?: string
}

export interface CategoryProps {
  categoryName: string
  description: string
  isActive?: any
  items?: any
  key?: any
  location: string
  menuCategoryContainerBorder?: string
  menuCategoryContainerBorderRadius?: string
  menuCategoryContainerBoxShadow?: string
  menuCategoryContainerDisplay?: string
  menuCategoryContainerFlexFlow?: string
  menuCategoryContainerMaxWidth?: string
  menuCategoryContainerOrderNumber?: string
  menuCategoryContainerWidth?: string
  menuCategoryDescriptionColor?: string
  menuCategoryDescriptionDisplay?: string
  menuCategoryDescriptionFontFamily?: string
  menuCategoryDescriptionFontSize?: string
  menuCategoryDescriptionFontWeight?: string
  menuCategoryDescriptionLetterSpacing?: string
  menuCategoryDescriptionLineHeight?: string
  menuCategoryDescriptionMargin?: string
  menuCategoryDescriptionMaxWidth?: string
  menuCategoryDescriptionPadding?: string
  menuCategoryDescriptionTextAlign?: string
  menuCategoryDescriptionTextTransform?: string
  menuCategoryItemsContainerDisplay?: string
  menuCategoryItemsContainerFlexFlow?: string
  menuCategoryItemsContainerJustifyContent?: string
  menuCategoryItemsContainerMargin?: string
  menuCategoryItemsContainerWidth?: string
  menuCategoryTitleColor?: string
  menuCategoryTitleDisplay?: string
  menuCategoryTitleFontFamily?: string
  menuCategoryTitleFontSize?: string
  menuCategoryTitleFontWeight?: string
  menuCategoryTitleLetterSpacing?: string
  menuCategoryTitleMargin?: string
  menuCategoryTitlePadding?: string
  menuCategoryTitleTextAlign?: string
  menuCategoryTitleTextTransform?: string
  menuItemBackground?: string
  menuItemBorder?: string
  menuItemBorderRadius?: string
  menuItemBoxShadow?: string
  menuItemDescriptionColor?: string
  menuItemDescriptionFontFamily?: string
  menuItemDescriptionFontSize?: string
  menuItemDescriptionFontWeight?: string
  menuItemDescriptionLetterSpacing?: string
  menuItemDescriptionLineHeight?: string
  menuItemDescriptionMaxWidth?: string
  menuItemDescriptionPadding?: string
  menuItemDescriptionTextAlign?: string
  menuItemDescriptionTextTransform?: string
  menuItemDisplay?: string
  menuItemFlexBasis?: string
  menuItemFlexFlow?: string
  menuItemMargin?: string
  menuItemMaxWidth?: string
  menuItemNameColor?: string
  menuItemNameFontFamily?: string
  menuItemNameFontSize?: string
  menuItemNameFontWeight?: string
  menuItemNameLetterSpacing?: string
  menuItemNameLineHeight?: string
  menuItemNameMaxWidth?: string
  menuItemNamePadding?: string
  menuItemNameTextAlign?: string
  menuItemNameTextTransform?: string
  menuItemPadding?: string
  menuItemPriceColor?: string
  menuItemPriceFontFamily?: string
  menuItemPriceFontSize?: string
  menuItemPriceFontWeight?: string
  menuItemPriceLetterSpacing?: string
  menuItemPriceLineHeight?: string
  menuItemPriceMaxWidth?: string
  menuItemPricePadding?: string
  menuItemPriceTextAlign?: string
  menuItemPriceTextTransform?: string
  menuItemTableDataLineHeight?: string
  menuItemTableDataPadding?: string
  menuItemTableFontFamily?: string
  menuItemTablePadding?: string
  menuItemTableWidth?: string
  menuItemWidth?: string
  orderNumber?: string
  sku?: string
  slug?: string
}
